language: ruby
before_install:
  - gem install bundler
rvm:
  - ruby-head
  - jruby-head
  - 2.4.2
  - 2.3.5
  - 2.2.8
  - jruby-9.1.13.0
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
